name: CI

on:
  pull_request:
  push:
    branches: [ main, develop ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Pre-commit
        run: |
          pre-commit run --all-files || (git status --porcelain; exit 1)
